<a href="https://colab.research.google.com/github/NagaSaiRamu/Data-Analytics-/blob/main/filteringDataSets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('House_Rent_Dataset.csv')
df.sample(5)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
1598,2022-05-27,1,4500,600,1 out of 4,Super Area,Madanayakahalli,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
1900,2022-07-04,2,6000,600,2 out of 3,Super Area,Chikkabanavara,Bangalore,Semi-Furnished,Bachelors/Family,1,Contact Owner
552,2022-06-20,1,25000,375,1 out of 22,Super Area,Lal Baug,Mumbai,Unfurnished,Bachelors/Family,1,Contact Owner
1302,2022-07-09,4,140000,2000,6 out of 45,Carpet Area,"DB Woods, Gokuldham",Mumbai,Furnished,Family,4,Contact Agent
613,2022-05-31,2,50000,1000,4 out of 7,Super Area,Ghatkopar East,Mumbai,Semi-Furnished,Bachelors/Family,2,Contact Owner

In [ ]:
df[df['City']=='Hyderabad']

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
3878,2022-06-28,4,75000,3800,3 out of 10,Carpet Area,"Financial District, Nanakram Guda",Hyderabad,Semi-Furnished,Bachelors/Family,4,Contact Agent
3879,2022-06-30,4,250000,4500,Ground out of 2,Carpet Area,Jubilee Hills,Hyderabad,Semi-Furnished,Family,4,Contact Agent
3880,2022-05-20,2,10000,1100,1 out of 3,Super Area,Meerpet,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
3881,2022-07-10,3,60000,3200,1 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
3882,2022-05-12,2,12000,647,2 out of 3,Super Area,Moti Nagar,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [ ]:
df[(df["City"]=='Hyderabad') & (df['Rent']<5000 )]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
3959,2022-04-30,1,4000,300,3 out of 3,Super Area,in Syed Ali Guda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
3990,2022-06-25,1,4000,400,Ground out of 1,Super Area,Borabanda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4043,2022-05-16,1,4500,60,1 out of 2,Super Area,"Hayathnagar, NH 9",Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4076,2022-05-31,3,1200,2100,1 out of 3,Carpet Area,"Uppal, NH 2 2",Hyderabad,Furnished,Bachelors/Family,3,Contact Owner
4201,2022-06-24,1,4700,850,3 out of 3,Super Area,"in Boduppal, NH 2 2",Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4220,2022-07-06,1,3000,80,Ground out of 2,Super Area,Rhoda Mistri Nagar,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4297,2022-05-12,1,3300,200,Ground out of 2,Super Area,Moula Ali,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4415,2022-06-06,1,3000,100,1 out of 2,Super Area,New Nallakunta,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4586,2022-06-14,1,4000,500,2 out of 3,Super Area,Almasguda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4706,2022-04-30,1,4500,50,4 out of 5,Super Area,Amberpet,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner

In [ ]:
df[((df['City']=='Bangalore') |(df['City']=='Hyderabad') )& (df['Rent']<5000)]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
1525,2022-06-20,1,4500,450,Ground out of 3,Super Area,Nelamangala,Bangalore,Semi-Furnished,Bachelors/Family,1,Contact Owner
1572,2022-05-23,1,4000,650,1 out of 2,Super Area,Byatarayanapura,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
1598,2022-05-27,1,4500,600,1 out of 4,Super Area,Madanayakahalli,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
1768,2022-06-04,1,4500,600,Ground out of 3,Super Area,"Peenya Industrial Area, Tumkur Road",Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
1776,2022-05-19,1,3500,150,2 out of 3,Super Area,Yeshwantpur,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
2053,2022-05-19,1,4300,300,2 out of 4,Super Area,Ragavendra Nagar,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
2057,2022-05-07,1,4800,580,Ground out of 1,Super Area,Kengeri,Bangalore,Semi-Furnished,Bachelors/Family,1,Contact Owner
2082,2022-06-04,1,4000,250,2 out of 3,Super Area,Btm Layout,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
2247,2022-05-05,1,4700,500,1 out of 4,Super Area,Chikkabanavara,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
2256,2022-04-27,1,4750,200,2 out of 2,Carpet Area,"Chamundeshwari Layout, Arakere",Bangalore,Semi-Furnished,Bachelors/Family,1,Contact Owner
2293,2022-05-23,1,4000,250,Ground out of 2,Super Area,Vijayanagar,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
2325,2022-05-27,1,4000,100,2 out of 3,Super Area,"Itc Colony, Maruthi Sevanagar",Bangalore,Semi-Furnished,Bachelors/Family,2,Contact Owner
2353,2022-07-07,1,4500,300,3 out of 3,Super Area,"Virat Nagar, Bommanahalli",Bangalore,Semi-Furnished,Bachelors/Family,1,Contact Owner
2362,2022-06-20,1,4500,200,4 out of 5,Super Area,T Dasarahalli,Bangalore,Unfurnished,Bachelors/Family,1,Contact Owner
3959,2022-04-30,1,4000,300,3 out of 3,Super Area,in Syed Ali Guda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
3990,2022-06-25,1,4000,400,Ground out of 1,Super Area,Borabanda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4043,2022-05-16,1,4500,60,1 out of 2,Super Area,"Hayathnagar, NH 9",Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4076,2022-05-31,3,1200,2100,1 out of 3,Carpet Area,"Uppal, NH 2 2",Hyderabad,Furnished,Bachelors/Family,3,Contact Owner
4201,2022-06-24,1,4700,850,3 out of 3,Super Area,"in Boduppal, NH 2 2",Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4220,2022-07-06,1,3000,80,Ground out of 2,Super Area,Rhoda Mistri Nagar,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4297,2022-05-12,1,3300,200,Ground out of 2,Super Area,Moula Ali,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4415,2022-06-06,1,3000,100,1 out of 2,Super Area,New Nallakunta,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4586,2022-06-14,1,4000,500,2 out of 3,Super Area,Almasguda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4706,2022-04-30,1,4500,50,4 out of 5,Super Area,Amberpet,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner

In [ ]:
df[df['Area Locality'].str.startswith('Kotha')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
1850,2022-04-29,2,12000,1400,2 out of 4,Super Area,Kothanur,Bangalore,Semi-Furnished,Bachelors/Family,2,Contact Owner
2375,2022-05-12,4,65000,3200,18 out of 19,Carpet Area,Kothanur,Bangalore,Semi-Furnished,Bachelors/Family,3,Contact Agent
3899,2022-05-12,1,10500,500,Ground out of 4,Super Area,Kothapet,Hyderabad,Furnished,Bachelors/Family,1,Contact Owner
3980,2022-07-02,2,20000,1600,1 out of 2,Super Area,Kothapet,Hyderabad,Unfurnished,Family,3,Contact Owner
4124,2022-04-30,2,18000,1248,4 out of 5,Carpet Area,Kothapet,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4171,2022-04-30,1,7000,950,1 out of 5,Super Area,Kothapet,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4214,2022-05-12,2,7500,950,1 out of 2,Super Area,Kothapet,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4343,2022-05-09,2,12000,1000,2 out of 2,Super Area,Kothapet,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner

In [ ]:
df[df['Area Locality'].str.endswith('t')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
9,2022-06-20,2,10000,1000,1 out of 3,Carpet Area,Natunhat,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner
16,2022-05-17,2,6000,600,1 out of 2,Super Area,Barasat,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
25,2022-05-22,2,7000,1000,1 out of 1,Super Area,Rajarhat,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
75,2022-06-18,2,12500,950,1 out of 4,Super Area,"Magnolia Prestige, Rajarhat",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner
87,2022-06-25,2,22000,800,4 out of 4,Super Area,"Hazra, Kalighat",Kolkata,Furnished,Bachelors/Family,1,Contact Agent
...,...,...,...,...,...,...,...,...,...,...,...,...
4674,2022-05-29,2,14000,1200,2 out of 3,Super Area,Amberpet,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4684,2022-07-05,1,7000,650,3 out of 3,Super Area,Karmanghat,Hyderabad,Semi-Furnished,Bachelors/Family,1,Contact Owner
4700,2022-07-06,1,7500,650,2 out of 4,Carpet Area,Begumpet,Hyderabad,Semi-Furnished,Bachelors,1,Contact Agent
4701,2022-07-06,1,7500,850,3 out of 5,Carpet Area,Begumpet,Hyderabad,Semi-Furnished,Bachelors,1,Contact Agent
4706,2022-04-30,1,4500,50,4 out of 5,Super Area,Amberpet,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner

In [ ]:
df[df['Area Locality'].str.contains('KPHB')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
4039,2022-07-07,2,19800,1070,3 out of 4,Carpet Area,KPHB Road,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4319,2022-06-18,1,9000,500,4 out of 4,Super Area,KPHB Road,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner

In [ ]:
df[df['Area Locality'].str.contains('Hyderabad')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
3931,2022-05-18,2,9000,1800,1 out of 1,Super Area,"Basheer Bagh, Hyderabad,",Hyderabad,Furnished,Bachelors/Family,2,Contact Owner